# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6312b56bf2829f7a949b95841583062c15e5305489b1ba395ecd89663a433a393e4734463fe9d8c94fd4f3a45575762b75dde983b55882fb1a5b4c3f83143297

test:
  secret_key_base: 0c5b46c5a78d1661b5a684887a27a16b9348d751a98ed19a26de44931b95db90180bdecf22b00f19abaa54d7cbc8a2284de28784adffc551d8dde1b728dfe850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
